spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 169228060507-p0ugl7rn2sc74e6dfp1uh91c083b6726.apps.googleusercontent.com
            clientSecret: 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
